#cloud-config
runcmd:
  - [ sh, -xc, "echo 'Download desired scripts'" ]
  - su - ec2-user -c "curl -G %%distribDirectoryUrl%%/graphql?query --data-urlencode '{desiredVersions (services: [\"scripts\"] ) { version } }' --output .scripts.version --retry 1000 --retry-delay 2 --connect-timeout 5"
  - su - ec2-user -c "curl %%distribDirectoryUrl%%/client-version-image/scripts/`jq -r data.desiredVersions[0].version /home/ec2-user/.scripts.version` --output .scripts.zip --retry 1000 --retry-delay 2 --connect-timeout 5"
  - su - ec2-user -c "unzip -o .scripts.zip update.sh"
  - su - ec2-user -c "unzip -jo .scripts.zip updater/*"
  - su - ec2-user -c "chmod +x *.sh"
  - [ sh, -xc, "echo 'Execute setup'" ]
  - su - ec2-user -c "./updater_setup.sh Azure %%name%% %%services%% %%distribDirectoryUrl%%"